# Generated by Django 5.2.7 on 2025-10-04 16:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitud (m)')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región/Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre común')),
                ('scientific_name', models.CharField(max_length=300, unique=True, verbose_name='Nombre científico')),
                ('plant_type', models.CharField(choices=[('tree', 'Árbol'), ('shrub', 'Arbusto'), ('flower', 'Flor'), ('crop', 'Cultivo'), ('grass', 'Pasto')], max_length=20, verbose_name='Tipo de planta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('typical_flowering_months', models.CharField(help_text='Meses típicos de floración (ej: Marzo-Mayo)', max_length=100, verbose_name='Meses de floración')),
                ('flowering_duration', models.PositiveIntegerField(default=30, help_text='Duración típica de floración en días', verbose_name='Duración floración (días)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Especie de planta',
                'verbose_name_plural': 'Especies de plantas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Identificador único para esta planta (ej: OAK_001_MADRID)', max_length=100, unique=True, verbose_name='Identificador')),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Roble del Parque del Retiro)', max_length=200, verbose_name='Nombre')),
                ('is_monitored', models.BooleanField(default=True, verbose_name='En monitoreo')),
                ('monitoring_start_date', models.DateField(verbose_name='Inicio monitoreo')),
                ('monitoring_end_date', models.DateField(blank=True, null=True, verbose_name='Fin monitoreo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('photo', models.ImageField(blank=True, upload_to='plants/photos/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.location', verbose_name='Ubicación')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plantspecies', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Monitor de planta',
                'verbose_name_plural': 'Monitores de plantas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FloweringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_date', models.DateTimeField(verbose_name='Fecha de detección')),
                ('flowering_stage', models.CharField(choices=[('bud', 'Capullo'), ('early', 'Floración temprana'), ('peak', 'Floración máxima'), ('late', 'Floración tardía'), ('end', 'Fin de floración')], max_length=20, verbose_name='Etapa de floración')),
                ('detection_method', models.CharField(choices=[('visual', 'Observación visual'), ('satellite', 'Detección satelital'), ('ai_model', 'Modelo de IA'), ('user_report', 'Reporte de usuario')], max_length=20, verbose_name='Método de detección')),
                ('confidence_score', models.FloatField(help_text='Nivel de confianza de la detección (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Confianza')),
                ('intensity', models.FloatField(blank=True, help_text='Intensidad de la floración (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Intensidad (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('photo', models.ImageField(blank=True, upload_to='flowering/photos/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('plant_monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plantmonitor', verbose_name='Planta')),
            ],
            options={
                'verbose_name': 'Evento de floración',
                'verbose_name_plural': 'Eventos de floración',
                'ordering': ['-detection_date'],
            },
        ),
    ]
