# Generated by Django 5.2.7 on 2025-10-04 22:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitedatapoint',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Punto geográfico específico si difiere de la ubicación principal', null=True, srid=4326, verbose_name='Coordenadas específicas'),
        ),
    ]
